# Generated by Django 3.2.6 on 2022-02-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_orders_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zip_code',
        ),
    ]
