# Generated by Django 3.2.6 on 2022-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[(1, 'Ordered'), (2, 'Preparing'), (3, 'Ready')], default=1, max_length=256),
        ),
    ]
