# Generated by Django 3.2.6 on 2022-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20220202_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('Ready', 'Ready')], default='Ordered', max_length=256),
        ),
    ]
