# Generated by Django 3.2.6 on 2022-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20220203_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
