# Generated by Django 3.1.3 on 2021-10-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='branch_name',
            field=models.CharField(default='Kalyan(West) UI0025', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='ifsc',
            field=models.CharField(default='UTI0025', max_length=100),
        ),
    ]
